server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tu_base_datos
    username: tu_usuario
    password: tu_contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


app:
  websocket:
    endpoint: /ws
    topic: /topic/notificaciones


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.tuempresa: DEBUG
