server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tu_base_datos
    username: tu_usuario
    password: tu_contraseña
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  websocket:
    endpoint: /ws
    topic: /topic/notificaciones

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.tuempresa: DEBUG
